In [2]:
import torch
import torchvision

torch.cuda.is_available()

array = torch.ones(5,5, requires_grad=True)

print(array)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)


In [11]:
import torch

a = torch.tensor([[2,2,1], [3,4,5], [6,7,8], [9,10,11]])

print(a)
print(a.shape)
print(a.size())

print(a.shape[0])

tensor([[ 2,  2,  1],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([4, 3])
torch.Size([4, 3])
4


#Reshape the tensor dimension

In [15]:
print(a.view(-1,1))

print(a.view(12, 1))

tensor([[ 2],
        [ 2],
        [ 1],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])
tensor([[ 2],
        [ 2],
        [ 1],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])


In [18]:
#3D tensors (channels, rows, columns)

three_dim = torch.randn(2,3,4)
print(three_dim)
print("\n******************************\n")
print(three_dim.view(2, 12))
print("\n******************************\n")
print(three_dim.view(2, -1))



tensor([[[ 0.8578, -0.7121,  1.3837,  0.9031],
         [-0.1250, -1.3077,  0.0886,  0.7294],
         [-1.0383, -0.6319,  0.4481, -0.7103]],

        [[ 0.7626,  1.0005,  0.5008, -0.6153],
         [ 0.1151,  0.9174, -0.1730,  0.9374],
         [ 0.5885, -0.0120,  0.2810,  0.9674]]])

******************************

tensor([[ 0.8578, -0.7121,  1.3837,  0.9031, -0.1250, -1.3077,  0.0886,  0.7294,
         -1.0383, -0.6319,  0.4481, -0.7103],
        [ 0.7626,  1.0005,  0.5008, -0.6153,  0.1151,  0.9174, -0.1730,  0.9374,
          0.5885, -0.0120,  0.2810,  0.9674]])

******************************

tensor([[ 0.8578, -0.7121,  1.3837,  0.9031, -0.1250, -1.3077,  0.0886,  0.7294,
         -1.0383, -0.6319,  0.4481, -0.7103],
        [ 0.7626,  1.0005,  0.5008, -0.6153,  0.1151,  0.9174, -0.1730,  0.9374,
          0.5885, -0.0120,  0.2810,  0.9674]])


In [20]:
#matrix with random numbers between 0 and 1
matrix = torch.rand(4,4)
print(matrix)
print(matrix.dtype)

tensor([[0.1002, 0.6578, 0.6423, 0.8285],
        [0.2666, 0.6869, 0.0666, 0.7031],
        [0.9933, 0.6408, 0.1023, 0.5333],
        [0.0381, 0.6088, 0.8807, 0.4147]])
torch.float32


##Numpy Bridge

In [22]:
import numpy

# move tensor to GPU
#r2 = r2.cuda()

CUDA = torch.cuda.is_available()
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

ModuleNotFoundError: No module named 'r2'