In [8]:
import torch
import torch.nn as nn

layer = nn.Linear(5,5)

print(layer.weight)
print(layer.weight.data)

nn.init.uniform_(layer.weight, a=0, b=3)
print(layer.weight)

#ini with normal distribution
nn.init.normal_(layer.weight, mean=0.0, std=0.2)
print(layer.weight)

#Constant value
nn.init.constant_(layer.bias, val=0)
print(layer.bias)

Parameter containing:
tensor([[ 0.4451, -0.1490, -0.1313,  0.1989,  0.4040],
        [-0.1652, -0.0869, -0.1109,  0.1376, -0.3376],
        [ 0.1665,  0.2896,  0.3344, -0.2596,  0.3618],
        [ 0.1180, -0.1405,  0.0140, -0.0428, -0.0244],
        [ 0.0334, -0.3557, -0.0804,  0.3417, -0.4186]], requires_grad=True)
tensor([[ 0.4451, -0.1490, -0.1313,  0.1989,  0.4040],
        [-0.1652, -0.0869, -0.1109,  0.1376, -0.3376],
        [ 0.1665,  0.2896,  0.3344, -0.2596,  0.3618],
        [ 0.1180, -0.1405,  0.0140, -0.0428, -0.0244],
        [ 0.0334, -0.3557, -0.0804,  0.3417, -0.4186]])
Parameter containing:
tensor([[2.5107, 0.1454, 1.9047, 2.4047, 2.8111],
        [1.6401, 1.8038, 0.8205, 1.3802, 0.3408],
        [2.5029, 2.3855, 1.4831, 2.2198, 0.5582],
        [0.6413, 0.1658, 0.9401, 1.8071, 2.3207],
        [2.3399, 2.1331, 2.7440, 0.8707, 0.7147]], requires_grad=True)
Parameter containing:
tensor([[-0.1767,  0.1455, -0.2772, -0.1425, -0.2235],
        [ 0.0525, -0.1868,  0.1276, 